global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'braintech-monitor'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  # Laravel Application metrics (custom)
  - job_name: 'laravel-app'
    static_configs:
      - targets: ['laravel-app:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # RAG System metrics (custom)
  - job_name: 'rag-system'
    static_configs:
      - targets: ['rag-system:8002']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Redis metrics (via Redis Exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Business metrics (custom endpoint)
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['laravel-app:80']
    metrics_path: '/api/metrics/business'
    scrape_interval: 60s